### ISSUE TITLE
Go through Android Launch Checklist

### ISSUE THREAD

**Issue by dotdoom** [dasfoo/delern#115]
https://developer.android.com/distribute/best-practices/launch/launch-checklist.html

**Comment by dotdoom** [comment]
Also don't forget to fix linter issues (see `app/lint.xml`).

**Comment by ksheremet** [comment]
[X] Understand the Developer Program Policies: no violations)

**Comment by dotdoom** [comment]
https://developer.android.com/distribute/best-practices/launch/launch-checklist.html

- [x] https://play.google.com/about/developer-content-policy/: acknowledged
- [x] Prepare your developer account: not selling as of now
- [ ] https://developer.android.com/distribute/best-practices/launch/localization-checklist.html: n/a yet
- [x] Plan for simultaneous releases: web released together (or earlier) than Android
- [ ] https://developer.android.com/develop/quality-guidelines/index.html: TBD (@ksheremet)
- [x] Build a release-ready APK: done
- [x] Plan your app’s Play Store listing: images done (screenshots see #473)
- [x] Upload your APK to the alpha or beta channel: done
- [x] Define your app’s device compatibility: done (minimal API level), n/a
- [x] Check the pre-launch reports: done
- [x] Setup your app’s price and countries of distribution: n/a
- [x] Opt-in to the right distribution options: n/a
- [x] Set up your in-app products and subscriptions: n/a
- [x] Determine your app’s content rating: done

**Comment by dotdoom** [comment]
https://developer.android.com/develop/quality-guidelines/core-app-quality.html

- [x] Visual design and user interaction (except UX-S1 point "a")
- [x] Functionality (partially)
- [x] Compatibility, performance and stability (partially)
- [x] Security (to be revisited continiuosly)
- [x] Google Play
- [x] Test procedures (some of them)
- [ ] Testing with StrictMode

**Comment by dotdoom** [comment]
Leaving this open for future releases, but moving into new Milestone.
