### ISSUE TITLE
Go through the Firebase Launch checklist

### ISSUE THREAD

**Issue by dotdoom** [dasfoo/delern#34]
https://firebase.google.com/support/guides/launch-checklist

**Comment by dotdoom** [comment]
[x] Update your connected apps: SHA-1 already present
[x] Know your plan limits: 1GB Firebase Database
[x] Prepare services
* Remote Config has proper configuration for release (no experiments)
* Analytics added
* Crash reporting set up and tested
[x] Cloud Messaging: n/a for Android
[x] Crash Reporting: using Crashlytics
[x] Realtime Database: ProGuard configured, Firebase Database Rules present
[x] Storage: n/a at this point
[x] Release: Test Lab set up, Dynamic Links n/a at this point.

Additionally, no new Firebase indexes seem necessary.

This is done for Beta, we'll have to repeat it for Release.

**Comment by ksheremet** [comment]
For release: 
- [x] Update your connected apps: SHA-1 already present
- [x] Know your plan limits: 1GB Firebase Database
- [x] Prepare services
    * Remote Config has proper configuration for release (no experiments)
    * Analytics added
    * Crash reporting set up and tested
- [x] Cloud Messaging: n/a for Android
- [x] Crash Reporting: using Crashlytics
- [x] Realtime Database: ProGuard configured, Firebase Database Rules present
- [x] Storage: n/a at this point
- [x] Release: Test Lab set up, Dynamic Links n/a at this point.
- [x] Authentication:
    * Google Sign-In set up.
- [] Personalize your OAuth consent screen https://console.developers.google.com/apis/credentials/consent?project=delern-e1b33.
- [x] Dinamic links n/a at this point https://firebase.google.com/docs/dynamic-links/

**Comment by dotdoom** [comment]
Based on the above, calling it done.
